config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'welcome/about'

  resources :games, only: [:index, :show, :new, :create, :update, :edit] do
    collection do
      get :find
      get :join
    end
  end

  resources :rooms
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates_presence_of :after_extra_turn_action, :extra_turns, :games_per_pairing, :host_id, :name, :players_per_table, :rounds
  validates_inclusion_of :active, :use_game_clock, in: [true, false]

  before_create :generate_game_code
  before_save :default_values

  enum after_extra_turn_action: [:nothing, :tie, :both_lose]

  belongs_to :host, foreign_type: :host_id, class_name: User
  has_and_belongs_to_many :users
  has_many :rooms

  private

  def default_values
    self.active = true if self.active.nil?
    self.after_extra_turn_action = 'none' if self.after_extra_turn_action.nil?
  end

  def generate_game_code
    code = (0...4).map { (65 + rand(26)).chr }.join
    code = (0...4).map { (65 + rand(26)).chr }.join while Game.find_by(code: code)
    self.code = code
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_host, except: [:find, :join]
  before_action :authenticate_user!, except: [:find]
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  def index
    @games = Game.where(host_id: current_user.id)
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params.permit(
      :after_extra_turn_action,
      :extra_turns,
      :games_per_pairing,
      :name,
      :players_per_table,
      :rounds,
      :time_per_round,
      :use_game_clock
    ))
    @game.host = current_user

    if @game.save
      @game.rooms = game_params[:rooms].map { |id| Room.find(id) }
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  def find
  end

  def join
    if @game = Game.find_by(code: params[:code])
      @game.users << current_or_guest_user unless @game.users.include?(current_or_guest_user)
      redirect_to @game
    else
      flash[:error] = "could not find game with code #{params[:code]}"
      redirect_to find_games_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(
        :after_extra_turn_action,
        :extra_turns,
        :games_per_pairing,
        :name,
        :players_per_table,
        :rounds,
        :time_per_round,
        :use_game_clock,
        rooms: []
      )
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.slim
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message
  = f.label :name
  = f.text_field :name
  br
  = f.label :rounds
  = f.number_field :rounds
  br
  = f.label :players_per_table
  = f.number_field :players_per_table
  br
  = f.label :games_per_pairing
  = f.number_field :games_per_pairing
  br
  = f.label :extra_turns
  = f.number_field :extra_turns
  br
  = f.label :after_extra_turn_action, "What happens after extra turns end?"
  = select("game", "after_extra_turn_action", Game.after_extra_turn_actions.keys)
  br
  = f.label :use_game_clock
  = f.check_box :use_game_clock
  br
  = f.label :time_per_round, "Time per round (minutes)"
  = f.number_field :time_per_round

  h2 Rooms

  = f.label :room_n
  = select_tag("game[rooms][]", options_from_collection_for_select(current_user.rooms, :id, :name), {prompt: 'Select a room'})
  br

  = link_to 'New Room', new_room_path
  .actions = f.submit

app/views/games/edit.html.slim
h1 Editing game

== render 'form'

= link_to 'Show', @game
'|
= link_to 'Back', games_path

app/views/games/find.html.slim
h1 Find a game

h2 Enter a game code
= form_tag join_games_path, method: :get do |f|
  = label_tag :game_code
  = text_field_tag :code
  .actions = submit_tag "Find Game"

app/views/games/index.html.slim
h1 Listing games

table
  thead
    tr
      th
      th
      th
      th

  tbody
    - @games.each do |game|
      tr
        td #{game.name}
        td = link_to 'Show', game
        td = link_to 'Edit', edit_game_path(game)
        td = link_to 'Destroy', game, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Game', new_game_path

app/views/games/show.html.slim
p#notice = notice

.page-header
  h1
    = @game.name
    small= " Round: #{@game.current_round} of #{@game.rounds} (#{@game.time_per_round} minutes)   "
    button.btn.btn-primary type="button" Start Round
  h3 Game Join Code: #{@game.code}

- @game.rooms.each do |room|
  h2= room.name
  table.table.table-striped
    thead
      tr
        th Table
        - @game.players_per_table.times do |i|
          th= "Player #{i + 1}"
        th Result
    tbody
      - room.tables.each do |table|
        tr
          td= table.name
          - table.users do |user|
            td user.name
          - (@game.players_per_table - table.users.count).times do
            td
              button.btn.btn-primary type="button" assign player to table
          td win/loss/draw


= link_to 'Edit', edit_game_path(@game)
'|
= link_to 'Back', games_path