config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'welcome/about'

  resources :games, only: [:index, :show, :new, :create, :update, :edit] do
    collection do
      get :find
      get :join
    end
  end

  resources :rooms
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates_presence_of :name

  has_many :tables, dependent: :destroy
  belongs_to :game
  belongs_to :host, foreign_type: :host_id, class_name: User
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :require_host
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  def index
    @rooms = Room.where(host_id: current_user.id)
  end

  # GET /rooms/1
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params.permit(:name))
    @room.host = current_user

    if @room.save
      @room.tables = room_params[:tables].map { |table| Table.new(name: table[:name]) }
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params.permit(:name))
      @room.tables = room_params[:tables].map do |table_hash|
        if table_id = table_hash.delete(:id)
          table = Table.find(table_id)
          table.update(table_hash)
          table
        else
           Table.new(table_hash)
        end
      end

      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  def find
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name, tables: [:id, :name])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.slim
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      h2 = "#{pluralize(@room.errors.count, "error")} prohibited this room from being saved:"
      ul
        - @room.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/rooms/edit.html.slim
h1 Editing room

= react_component 'RoomForm', initialRoom: @room, initialTables: @room.tables

= link_to 'Show', @room
'|
= link_to 'Back', rooms_path

app/views/rooms/index.html.slim
h1 Listing rooms

table
  thead
    tr
      th
      th
      th

  tbody
    - @rooms.each do |room|
      tr
        td = link_to 'Show', room
        td = link_to 'Edit', edit_room_path(room)
        td = link_to 'Destroy', room, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Room', new_room_path

app/views/rooms/new.html.slim
h1 New room
= react_component 'RoomForm'

= link_to 'Back', rooms_path

app/views/rooms/show.html.slim
p#notice = notice


= link_to 'Edit', edit_room_path(@room)
'|
= link_to 'Back', rooms_path