config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'welcome/about'

  resources :games, only: [:index, :show, :new, :create, :update, :edit] do
    collection do
      get :find
      get :join
    end
  end

  resources :rooms
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      - if current_user
        button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      a.navbar-brand href="#{default_user_path(current_or_guest_user)}" Game Reporter
    - if current_user
      - if current_user.host?
        ul.nav.navbar-nav
          li
            = link_to "Games", games_path
          li
            = link_to "Rooms", rooms_path
      - elsif current_user.player?
        ul.nav.navbar-nav
          li
            = link_to "Find a game", find_games_path
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              = current_user.name
              span.caret
            ul.dropdown-menu
              li
                a href="#"  Profile
              li
                a href="#"  Stats
              li
                = link_to('Logout', destroy_user_session_path)
    - elsif guest_user
      ul.nav.navbar-nav
        li
          = link_to "Find a game", find_games_path
      ul.nav.navbar-nav.navbar-right
        li
          =link_to "#{guest_user.name} | Log in", new_user_session_path
    - else
      ul.nav.navbar-nav.navbar-right
        li
          =link_to 'Log in', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title GameReporter
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'layouts/header'
    div.container
      p.notice= notice
      p.alert= alert
      = yield